"""Shared helpers for the Temporal SAE and Priors-in-Time report generators.

Both read the frozen run results rather than the prose written about them: `toy-temporal/`
for the toy runs, and `gemma-2-2b-tsae/`, `gemma-2-2b-pit/` and `gemma-2-2b/` for the released
checkpoints. A generator that read a findings file would make the paper agree with our summary
rather than with the run.

Captions are emitted as `TODO(caption)` on purpose. A caption states what a reader should take
from a figure, and that is a judgement for a person, not a format string.
"""
from __future__ import annotations

import json
import statistics as st
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "outputs"

# Results follow the repository's own layout, source then layer, the same shape
# `config.py` builds from `LAYER_RUN = f"{SOURCE_NAME}/layer_{LAYER:02d}"`. An earlier
# version put everything under `outputs/temporal/`, which named the folder after the
# intention rather than the contents: it held Matryoshka baselines too, and Matryoshka is
# not temporal. A layout that is an exception is the one that gets forgotten first.
TSAE = OUT / "gemma-2-2b-tsae" / "layer_12"
PIT = OUT / "gemma-2-2b-pit" / "layer_12"
MSAE = OUT / "gemma-2-2b" / "layer_12"
TOY = OUT / "toy-temporal"
DATA = TOY   # kept so callers that only read toy files need no change
DEFAULT_OUT = HERE.parent / "outputs" / "paper_figuers"

HEAD = (
    "% GENERATED by reporting/{gen}.py -- do not edit by hand.\n"
    "% Source: metrics/outputs/{{toy-temporal,gemma-2-2b*}}/ -- frozen run results, not prose.\n"
    "% Every caption is TODO on purpose: a caption is a claim about what to take away,\n"
    "% and this project requires those to be written by a person.\n"
    "% Regenerate:  python3 -m reporting.{gen}\n"
    "% Requires:    \\input{{thresholds_macros.tex}} in the preamble (defines \\MinJoint etc.),\n"
    "%              and packages booktabs, graphicx, amsmath.\n"
)

TODO = "TODO(caption, human-written). {}"


def toy_tsae() -> dict:
    """Temporal SAE toy runs, keyed by tree."""
    return json.loads((TOY / "tsae_results.json").read_text())["cells"]


def toy_pit() -> dict:
    """Priors in Time toy runs, keyed by condition."""
    return json.loads((TOY / "priors_in_time_results.json").read_text())["cells"]


# Guards that a metrics report must record before it may be used. A report written
# before BOS exclusion landed carries neither, and its numbers are not comparable with
# anything written after: BOS is an attention sink, so with 400 documents every feature
# pair in the dictionary collected 400 joint firings from that one position and cleared
# MIN_JOINT on its own. Such a file was used as the Matryoshka baseline for a day and
# inflated the T-SAE edge-density ratio from 794x to 1,760x. See
# outputs/gemma-2-2b/layer_12/withdrawn/README.md and ERROR_LOG 2026-09-11.
#
# The check is on absence, not value: these keys entered the config block together with
# the guards they name, so a report that omits one predates it.
_REQUIRED_CONFIG = ("bos_excluded", "min_joint")


def read(path: Path, *, require_guards: bool = True):
    """Load a JSON result, refusing a metrics report that predates the current guards.

    `require_guards` is on by default and should stay on for anything that becomes a
    number in the paper. Pass False only to inspect an old file deliberately.
    """
    if not path.is_file():
        return None
    d = json.loads(path.read_text())
    cfg = d.get("config")
    if require_guards and isinstance(cfg, dict) and "block_ranges" in cfg:
        missing = [k for k in _REQUIRED_CONFIG if k not in cfg]
        if missing:
            raise ValueError(
                f"{path} is a metrics report whose config omits {missing}, so it was "
                f"graded before those guards existed and cannot be compared with a "
                f"current report. It records {d.get('total_tokens')} tokens; current "
                f"gemma runs record 48,571. See "
                f"outputs/gemma-2-2b/layer_12/withdrawn/README.md."
            )
    return d


def ms(vals, p=3, pm=True):
    """mean, and the spread over seeds. One run has no spread and must not pretend to."""
    v = [x for x in vals if x is not None]
    if not v:
        return "--"
    if len(v) == 1 or not pm:
        return f"{st.mean(v):.{p}f}"
    return rf"{st.mean(v):.{p}f}\,$\pm$\,{st.pstdev(v):.{p}f}"


def esc(t) -> str:
    s = str(t)
    for a, b in (("\\", r"\textbackslash{}"), ("_", r"\_"), ("%", r"\%"),
                 ("&", r"\&"), ("#", r"\#")):
        s = s.replace(a, b)
    return s


def table(label, caption, header, rows, align=None, note=None, size="small"):
    r"""One booktabs table, caption above the rules, matching make_report_tables.table."""
    align = align or ("l" + "r" * (len(header) - 1))
    L = [r"\begin{table}[tbp]", r"  \centering", rf"  \{size}",
         rf"  \caption{{{caption}}}", rf"  \label{{tab:{label}}}",
         rf"  \begin{{tabular}}{{{align}}}", r"    \toprule",
         "    " + " & ".join(header) + r" \\", r"    \midrule"]
    L += ["    " + (r if isinstance(r, str)
                    else " & ".join(str(c) for c in r) + r" \\") for r in rows]
    L += [r"    \bottomrule", r"  \end{tabular}"]
    if note:
        L.append(rf"  \\[2pt] \footnotesize {note}")
    L.append(r"\end{table}")
    return "\n".join(L)


def figure(label, caption, path, width=r"\linewidth", note=None):
    L = [r"\begin{figure}[tbp]", r"  \centering",
         rf"  \includegraphics[width={width}]{{{path}}}",
         rf"  \caption{{{caption}}}", rf"  \label{{fig:{label}}}"]
    if note:
        L.append(rf"  \\[2pt] \footnotesize {note}")
    L.append(r"\end{figure}")
    return "\n".join(L)


def emit(out_dir: Path, filename: str, gen: str, parts) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    L = [HEAD.format(gen=gen)]
    for slot, section, tex in parts:
        if section:
            L += ["", "% " + "-" * 72, f"% {section}", "% " + "-" * 72]
        L += ["", f"% [{slot}]", tex]
    dest = out_dir / filename
    dest.write_text("\n".join(L) + "\n")
    return dest


# --------------------------------------------------------------------------- figure style
# Ink and muted match make_report_figures, so a reader moving between the two
# papers sees one system rather than two.
INK, MUTED = "#2B2B33", "#5A6B7B"


def text_on(bg: str) -> str:
    """Ink or white on `bg`, whichever the eye can actually read (WCAG luminance)."""
    from matplotlib import colors as mcolors

    def lum(c):
        lin = [v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4
               for v in mcolors.to_rgb(c)]
        return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]

    L = lum(bg)
    return "white" if 1.05 / (L + 0.05) > (L + 0.05) / (lum(INK) + 0.05) else INK


def tree_rates() -> dict:
    """Firing rate and count per role, read from the two tree configs.

    Read rather than transcribed: the decorrelated tree exists only to flip these
    two numbers, so a figure that hard-codes them cannot disagree with the world it
    is drawing. Returns {} if the sae-training checkout is not beside this one.
    """
    root = HERE.parent.parent / "sae-training" / "configs"
    out = {}
    for key, name in (("original", "tree.json"),
                      ("decorrelated", "tree_decorrelated.json")):
        f = root / name
        if not f.is_file():
            continue
        leaves = []

        def walk(n, depth=0):
            if n.get("is_read_out"):
                leaves.append((depth, n["active_prob"]))
            for c in n.get("children", []):
                walk(c, depth + 1)

        walk(json.loads(f.read_text()))
        # Depth 1 splits into parents and distractors by whether the node has
        # read-out children; the two share a depth and differ only in firing rate,
        # so they separate on rate: parents are the rarer group in exactly one of
        # the two trees, which is the whole point of having two.
        d1 = sorted({p for d, p in leaves if d == 1})
        par = min(d1, key=lambda p: sum(1 for d, q in leaves if d == 1 and q == p))
        out[key] = {
            "parent": (sum(1 for d, p in leaves if d == 1 and p == par), par),
            "distractor": (sum(1 for d, p in leaves if d == 1 and p != par),
                           next(p for p in d1 if p != par)),
            "child": (sum(1 for d, _ in leaves if d == 2),
                      next(p for d, p in leaves if d == 2)),
        }
    return out
